/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic outline for a simple desktop window.

  ==============================================================================
*/

#include "CommonHeader.h"
#include "MainWindow.h"
#include "MainComponent.h"
#include "StoredSettings.h"


//==============================================================================
MainAppWindow::MainAppWindow()
    : DocumentWindow (JUCEApplication::getInstance()->getApplicationName(),
                      Colours::lightgrey,
                      DocumentWindow::allButtons)
{
	StoredSettings::getInstance();												//call the constructor of StoredSettings to initialize it
	MainComponent* const comp = new MainComponent();
	command_manager->registerAllCommandsForTarget(comp);
	command_manager->registerAllCommandsForTarget(JUCEApplication::getInstance());
	setResizable(true, true);
	setContentOwned(comp, true);
	setMenuBar(comp);
	const Rectangle<int> display_size = Desktop::getInstance().getMainMonitorArea();
	setSize(display_size.getWidth()/2, display_size.getHeight()/2);
    centreWithSize (getWidth(), getHeight());
	addKeyListener(command_manager->getKeyMappings());
    setVisible (true);
}

MainAppWindow::~MainAppWindow()
{
	setMenuBar(nullptr);
}

void MainAppWindow::closeButtonPressed()
{
	command_manager->invokeDirectly(CommandIDs::CLOSE_ALL_FILES, false);
	if(dynamic_cast<MainComponent*>(getContentComponent())->IsQuitting()){
		JUCEApplication::getInstance()->quit();
	}
}
