/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "CommonHeader.h"
#include "MainWindow.h"
#include "StoredSettings.h"

#define BOOST_UTF8_BEGIN_NAMESPACE namespace utf8{
#define BOOST_UTF8_DECL
#define BOOST_UTF8_END_NAMESPACE }
#include <libs/detail/utf8_codecvt_facet.cpp>
#undef BOOST_UTF8_DECL
#undef BOOST_UTF8_BEGIN_NAMESPACE
#undef BOOST_UTF8_END_NAMESPACE

ApplicationCommandManager* command_manager = 0;


//==============================================================================
class OpenBVEEditorApplication  : public JUCEApplication
{
public:
    //==============================================================================
    OpenBVEEditorApplication()
    {
    }

    ~OpenBVEEditorApplication()
    {
    }

    //==============================================================================
    void initialise (const String&)
    {
        // Do your application's initialisation code here..
		command_manager = new ApplicationCommandManager();
		// set the locale in case of Japanese..
		std::locale loc;
		loc = std::locale(loc, new utf8::utf8_codecvt_facet());
		std::locale::global(loc);
        mainWindow = new MainAppWindow();
    }

    void shutdown()
    {
        // Do your application's shutdown code here..
        mainWindow = 0;
		StoredSettings::deleteInstance();
		deleteAndZero(command_manager);
    }

    //==============================================================================
    void systemRequestedQuit()
    {
		mainWindow->closeButtonPressed();
    }

    //==============================================================================
    const String getApplicationName()
    {
        return "OpenBVEEditor";
    }

    const String getApplicationVersion()
    {
        return ProjectInfo::versionString;
    }

    bool moreThanOneInstanceAllowed()
    {
        return false;
    }

    void anotherInstanceStarted (const String&)
    {
        
    }

	void unhandledException(const std::exception* e, const String& sourceFileName, int lineNumber)
	{
		DBG(String("an error has occured in ") + sourceFileName + String(" at line ") + String(lineNumber));
		AlertWindow::showMessageBox(AlertWindow::WarningIcon, "Error", e->what());
		systemRequestedQuit();
	}

private:
    ScopedPointer <MainAppWindow> mainWindow;
};

//==============================================================================
// This macro generates the main() routine that starts the app.
START_JUCE_APPLICATION(OpenBVEEditorApplication)
